### PR TITLE
User Interface of Sign Up Screen (All stages), Move Radio and ImageUpload to components

### PR DESCRIPTION
**Pull request by SPK137**
- Stage 1
image
image
- Stage 3
image
image
- Stage 4
image

### CODE REVIEW

**Review by pointmekin — COMMENTED** [review]
LGTM. But i think there's one text that's not i18n yet na.

**Review by bweam — COMMENTED** [review]
LGTM please check what Point has commented again

**Review by bweam — APPROVED** [review]
LGTM

**Comment by SPK137** [comment]
> LGTM. But i think there's one text that's not i18n yet na.

Where is that? Can you point it out?

**Comment by pointmekin** [comment]
> > LGTM. But i think there's one text that's not i18n yet na.
> 
> Where is that? Can you point it out?

My bad. I think I accidentally looked at the removed changes then... I looked and can't find either. Sorry2

**Review by pointmekin — APPROVED** [review]

**Pull request merged**
