### PR TITLE
Note/memory recall elderly

### PR DESCRIPTION
**Pull request by Panoj-k**
Add memory recall screens for elderly

- Welcome screen
image

- Choice quiz
image

- Short-answer quiz
image

- Guide
image

- Finish screen
image

- Translation TH-EN

### CODE REVIEW

**Comment by bweam** [comment]
shouldn't there be no gap for image on questions without an image? (your second screenshot)

**Comment by Panoj-k** [comment]
> shouldn't there be no gap for image on questions without an image? (your second screenshot)

**Comment by Panoj-k** [comment]
> shouldn't there be no gap for image on questions without an image? (your second screenshot)

There is an issue with the URL of the image. I add a white fallback image to it, so there is a gap.

**Review by chuwong35122 — APPROVED** [review]
lgtm

**Pull request merged**
